### ISSUE TITLE
Recherche globale multi-catalogues

### ISSUE THREAD

**Issue by fvanderbiest** [inspireteam/geogw#3]
Actuellement on peut faire une recherche textuelle sur un catalogue, ex: http://inspire.sgmap.fr/api/services/5387a37d785588482f5acb45/datasets?offset=0&q=algues

Il serait très intéressant à mon sens de pouvoir lancer une requête sur tous les catalogues référencés, ex: http://inspire.sgmap.fr/api/datasets?offset=0&q=algues

A moins que ce ne soit du ressort de l'API de data.gouv.fr ?

Cette fonctionnalité me permettrait par exemple de proposer un addon intéressant au visualiseur geOrchestra (cf par exemple http://sdi.georchestra.org/mapfishapp/ > add layers > catalog --> actuellement limité à une recherche mono-catalogue)

**Comment by Guts** [comment]
:+1:

**Comment by jdesboeufs** [comment]
Sur quel critère pensez-vous qu'on peut s'appuyer pour une première version ?
Je prend la version la plus récente du Record, quel que soit le catalogue ?

**Comment by fvanderbiest** [comment]
> Je prend la version la plus récente du Record, quel que soit le catalogue ?

Yep !

**Comment by jdesboeufs** [comment]
Done!
Cf https://inspire.data.gouv.fr
Issues for this instance should be posted at https://github.com/sgmap/inspire-next/issues
